### ISSUE TITLE
[Idea] Reusable workflows

### ISSUE THREAD

**Issue by garden-of-delete** [salesforce/orchard#12]
The current design uses two separate API requests for workflow definition and activation / instantiation. Workflows seem to be oriented towards single-use. Alternatives that seem clearer to me would be:
1. Use a single API request to define and schedule activation of the workflow. Workflows continue to be single-use.
2. Continue to define and activate workflows independently. Persist workflows in the postgres db to make them reusable / reference-able as a dependency by other workflows. Could even introduce the idea of a workflow template to make defining variants of some common workflow easy.

Curious what folks think about this? Am I missing something about the intended use pattern for Orchard?

**Comment by realstraw** [comment]
@garden-of-delete separated activation step is mainly to keep it more align with AWS data pipeline API at this stage. There is no particular reason to separate them and we might want to revisit this later to simplify the workflow in v2
